# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"

#   # annotations:
#   #   nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: asd.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: mongo-express-service
#                 port:
#                   number: 8081

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: issuer
  labels:
    app.kubernetes.io/instance: mongo-express
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/version: 1.16.0
    argocd.argoproj.io/instance: mongo-express
    helm.sh/chart: mongo-express-0.2.0
  name: mongo-express
  namespace: myapp
spec:
  ingressClassName: nginx
  rules:
    - host: ddddd.com
      http:
        paths:
          - backend:
              service:
                name: ms-payment-quoting
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
