apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/debrecenid/argocd-app-config.git
    targetRevision: HEAD
    path: mongo-express
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
