apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
    argocd.argoproj.io/instance: postgres
    helm.sh/chart: postgresql-10.12.0
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: postgres-postgresql-headless
  namespace: myapp
spec:
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
  type: ClusterIP
