apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
    argocd.argoproj.io/instance: postgres
    helm.sh/chart: postgresql-10.12.0
  name: postgres-postgresql
  namespace: myapp
spec:
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
    role: primary
  type: ClusterIP
